version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      MSSQL_SA_PASSWORD: P@ssw0rd
      ACCEPT_EULA: Y
    cap_add:
      - SYS_PTRACE
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - dotnet-network
      
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5001:5001"
    volumes:
      - './:/app'
    depends_on:
      - sqlserver
    networks:
      - dotnet-network

  localtunnel:
    image: efrecon/localtunnel
    restart: unless-stopped
    command:
      --local-host app --port 5001 --subdomain chillpay-dev
    depends_on:
      - app
    networks:
      - dotnet-network
      
volumes:
  sqlserver-data:

networks:
  dotnet-network:
